services:
  app.listener.add_funds_wallet:
    class: WalletBundle\EventListener\WalletListener
    arguments: [@doctrine.orm.default_entity_manager]
    tags:
      - { name: kernel.event_listener, event: add_funds_wallet, method: addFundsWallet }

  app.listener.payout_wallet:
      class: WalletBundle\EventListener\WalletListener
      arguments: [@doctrine.orm.default_entity_manager]
      tags:
        - { name: kernel.event_listener, event: payout_wallet, method: payoutWallet }